   <!-- start branding space include -->
   <table border="0" width="100%" cellspacing="0" cellpadding="0" summary="This table contains the branding banner and image.">
    <tr>
     <td valign="middle" class="banner">
      <img src="/template-assets/images/150_years.gif" alt="150 years of Achievement" hspace="0" vspace="0" border="0" width="292" height="70" align="left" /></td>
     <td align="right" class="banner">
      <img src="/template-assets/images/medfac.jpg" hspace="0" vspace="0" border="0" width="300" height="70" alt="Image of university students and staff" align="right" />
     </td>
    </tr>
   </table> 
   <!-- end branding space include -->