   <!-- start g_footer include -->
   <p>&copy; The University of Melbourne 1994-2003<br />
   The University of Melbourne <acronym title="Australian Business Number">ABN</acronym>: 84 002 705 224<br />
   <acronym title="Commonwealth Register of Institutions and Courses for Overseas Students">CRICOS</acronym> Provider Number: 00116K ( <a href="http://www.services.unimelb.edu.au/international/visas/index.html" accesskey="i" title="Information about student visas, work visas, extensions and course transfers">More information</a> )<br />
   <a href="http://www.services.unimelb.edu.au/admissions/" accesskey="e" title="Course enquiries, admissions, course search, courses and programs">Course Enquiries</a><br />
   </p>
   <!-- end footer include -->