<!-- start g_footbar_rhs include -->
<td class="footbar" nowrap="nowrap">
   <span id="contactbar"><a href="http://www.unimelb.edu.au/contact/index.html" accesskey="o" title="How to contact the University of Melbourne">Contact the University</a> : <a href="http://www.unimelb.edu.au/disclaimer/" accesskey="d" title="Caution notice and copyright notice">Disclaimer &amp; Copyright</a> : <a href="http://www.unimelb.edu.au/disclaimer/privacy.html" accesskey="p" title="Privacy for students and staff, freedom of information">Privacy</a> : <a href="http://www.unimelb.edu.au/accessibility/" accesskey="a" title="Accessibility features of the website">Accessibility</a></span>
</td>
<!-- end g_footbar_rhs include -->