  <!-- start g_quick_links include -->
   <table cellpadding="0" cellspacing="0" border="0" align="right" summary="This table contains links to the top levels on the University website.">
    <tr>
     <td>
      <img src="/template-assets/images/grey_nav_curve.gif" alt="" width="50" height="29" hspace="0" vspace="0" border="0" align="left" />
     </td>
     <td class="secondnav">
      <a href="http://www.unimelb.edu.au/az/faculties.html" accesskey="f" title="
      Listing of Faculties">Faculties</a> : <a href="http://www.unimelb.edu.au/az/index.html" accesskey="a" title="An A to Z directory of faculties and departments">A-Z Directory</a> : <a href="http://www.lib.unimelb.edu.au/" accesskey="l" title="University Library">Library</a>
     </td>
    </tr>
   </table>
  <!-- end secondnav include -->