    <!-- start g_search_label include -->
    <form method="get" action="http://websearch.its.unimelb.edu.au/query.html" name="searchform" id="searchform">
    <input type="hidden" name="qp" value="" />
    <input type="hidden" name="col" value="unimelb" />
    <input type="hidden" name="ht" value="0" />
    <input type="hidden" name="qs" value="" />
    <input type="hidden" name="qc" value="" />
    <input type="hidden" name="pw" value="100%" />
    <input type="hidden" name="ws" value="0" />
    <input type="hidden" name="qm" value="0" />
    <input type="hidden" name="st" value="1" />
    <input type="hidden" name="nh" value="25" />
    <input type="hidden" name="lk" value="1" />
    <input type="hidden" name="rf" value="0" />
    <input type="hidden" name="rq" value="0" />
    <input type="hidden" name="si" value="1" />
    <table cellpadding="0" cellspacing="2" border="0" align="right" summary="This table contains the input box for the University search engine.">
     <tr>
      <td class="topnavcell" valign="middle" nowrap="nowrap">
       <label for="searchtext"><span class="topnavlabel">Uni Search: </span></label></td>
       <td class="topnavcell" nowrap="nowrap">
       <input class="searchtext" style="height:15px;border:solid 1px #7898b5;" type="text" name="qt" value=" University site search" size="24" accesskey="s" onfocus="focusField(this, ' University site search')" onblur="blurField(this, ' University site search')" />
      </td>
      <td valign="middle">
       <input type="image" name="Search" value="Search" src="/template-assets/images/btn_search_top.gif" style="display:block;" accesskey="s" alt="Search" />
      </td>
     </tr>
    </table>
   </form>
   <!-- end g_search_label include -->
